"""Generation of a *proposed* PowerShell remediation.

Used when the diagnosis is confident but no approved runbook covers the case
(spec section 7, option 2). The generator is a template renderer, not a free-text
model call: the shape of the script is fixed source code here, and only
already-validated parameter values are substituted.

A generated script is always:
  * parameterised - no hard-coded target, subscription or credential,
  * error-handled and idempotent,
  * emitted with explicit pre-check / change / post-check phases,
  * marked `script_source="generated"`, which the policy engine treats as
    NOT executable: it is shown to the engineer to review and publish through
    change control. Production execution only ever runs published runbooks.
"""

from __future__ import annotations

from typing import Any

from ..security.validators import validate_resource_group, validate_resource_name
from .validator import ValidationReport, validate_script

_TEMPLATE = '''<#
.SYNOPSIS
    {synopsis}

.DESCRIPTION
    PROPOSED remediation generated by the AVD AI agent for incident {incident_id}.

    THIS SCRIPT HAS NOT BEEN PUBLISHED AS AN APPROVED RUNBOOK. Review it, then
    publish it to the Automation account through change control before it can
    be executed against production.

    Root cause    : {root_cause}
    Evidence      : {evidence}
    Risk          : {risk}
    Expected impact: {impact}

.NOTES
    Generated     : for review only
    Executes as   : Automation account Managed Identity (no stored credentials)
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{{0,78}}[A-Za-z0-9_]$')]
    [string]$VmName,

    [Parameter(Mandatory)]
    [ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._()-]{{0,88}}[A-Za-z0-9_()-]$')]
    [string]$ResourceGroupName,
{extra_params}
    [Parameter()]
    [string]$CorrelationId = [guid]::NewGuid().ToString()
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Write-Step {{
    param([string]$Phase, [string]$Message, [string]$Status = 'info')
    ([ordered]@{{
        correlationId = $CorrelationId; runbook = '{name}'
        phase = $Phase; status = $Status; message = $Message
        timestamp = (Get-Date).ToUniversalTime().ToString('o')
    }} | ConvertTo-Json -Compress) | Write-Output
}}

try {{
    Write-Step -Phase 'auth' -Message 'Connecting with the Automation Managed Identity.'
    $null = Connect-AzAccount -Identity -ErrorAction Stop

    # ---- Validation: confirm the target exists and is in the expected state
    Write-Step -Phase 'validate' -Message "Resolving $VmName in $ResourceGroupName."
    $vm = Get-AzVM -ResourceGroupName $ResourceGroupName -Name $VmName -Status -ErrorAction Stop
    $powerState = ($vm.Statuses | Where-Object Code -like 'PowerState/*').DisplayStatus
    if ($powerState -ne 'VM running') {{
        Write-Step -Phase 'validate' -Status 'failed' -Message "VM power state is '$powerState'."
        throw "Precondition failed: VM is not running."
    }}

    # ---- Pre-check ---------------------------------------------------------
{pre_check}

    # ---- Remediation -------------------------------------------------------
    if ($PSCmdlet.ShouldProcess($VmName, '{action_title}')) {{
{remediation}
    }}

    # ---- Post-check --------------------------------------------------------
{post_check}

    Write-Step -Phase 'complete' -Status 'succeeded' -Message 'Remediation completed successfully.'
    exit 0
}}
catch {{
    Write-Step -Phase 'error' -Status 'failed' -Message $_.Exception.Message
    Write-Error $_
    throw
}}
'''

_SERVICE_PRE = """    $preScript = "Get-Service -Name '{service}' | Select-Object -ExpandProperty Status"
    $pre = Invoke-AzVMRunCommand -ResourceGroupName $ResourceGroupName -VMName $VmName `
        -CommandId 'RunPowerShellScript' -ScriptString $preScript
    Write-Step -Phase 'pre-check' -Message "{service} = $($pre.Value[0].Message.Trim())\""""

_SERVICE_FIX = """        $fixScript = @'
$ErrorActionPreference = 'Stop'
$svc = Get-Service -Name '{service}'
if ($svc.StartType -eq 'Disabled') {{
    throw 'Service start type is Disabled; refusing to change configuration.'
}}
if ($svc.Status -ne 'Running') {{ Start-Service -Name '{service}' ; Start-Sleep -Seconds 8 }}
(Get-Service -Name '{service}').Status.ToString()
'@
        Write-Step -Phase 'remediate' -Message 'Starting {service}.'
        $null = Invoke-AzVMRunCommand -ResourceGroupName $ResourceGroupName -VMName $VmName `
            -CommandId 'RunPowerShellScript' -ScriptString $fixScript"""

_SERVICE_POST = """    $postScript = "Get-Service -Name '{service}' | Select-Object -ExpandProperty Status"
    $post = Invoke-AzVMRunCommand -ResourceGroupName $ResourceGroupName -VMName $VmName `
        -CommandId 'RunPowerShellScript' -ScriptString $postScript
    $postStatus = $post.Value[0].Message.Trim()
    Write-Step -Phase 'post-check' -Message "{service} = $postStatus"
    if ($postStatus -notmatch 'Running') {{
        Write-Step -Phase 'post-check' -Status 'failed' -Message '{service} did not reach Running.'
        throw 'Verification failed: {service} is not Running.'
    }}"""


class GeneratedScript:
    def __init__(self, name: str, script: str, report: ValidationReport) -> None:
        self.name = name
        self.script = script
        self.report = report

    @property
    def safe(self) -> bool:
        return self.report.passed


def generate_service_remediation(
    *,
    incident_id: str,
    service_name: str,
    vm_name: str,
    resource_group: str,
    root_cause: str,
    evidence: list[str],
    risk: str = "low",
    impact: str = "One service is started. No session is disconnected.",
) -> GeneratedScript:
    """Render a service-start remediation for a service with no dedicated runbook."""
    vm_name = validate_resource_name(vm_name, parameter="vmName")
    resource_group = validate_resource_group(resource_group)
    # The service name is *not* interpolated from free text: callers must pass a
    # value that already passed security.validators.validate_service_name.
    name = f"Repair-{service_name}-Proposed"
    script = _TEMPLATE.format(
        synopsis=f"Start the {service_name} service on one AVD session host.",
        incident_id=incident_id,
        root_cause=root_cause,
        evidence="; ".join(evidence[:4]) or "see incident record",
        risk=risk,
        impact=impact,
        name=name,
        action_title=f"Start service {service_name}",
        extra_params="",
        pre_check=_SERVICE_PRE.format(service=service_name),
        remediation=_SERVICE_FIX.format(service=service_name),
        post_check=_SERVICE_POST.format(service=service_name),
    )
    return GeneratedScript(name, script, validate_script(script, generated=True))


def describe_generation_policy() -> dict[str, Any]:
    return {
        "generated_scripts_executable": False,
        "reason": (
            "Production execution starts runbooks already published to the Azure "
            "Automation account. A generated script is a review artefact: publish "
            "it through change control to make it executable."
        ),
    }
